name: Deploy Hexo to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 权限配置（官方方案优化）[3](@ref)
permissions:
  contents: read
  pages: write
  id-token: write
  actions: write  # 新增权限解决 API 调用问题

# 并发控制（避免部署冲突）
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      # 2. 安装 Pandoc（渲染器依赖）
      - name: Install Pandoc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
        # 验证安装
      - name: Check Pandoc Version
        run: pandoc --version

      # 3. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 4. 缓存 node_modules 加速构建 [6](@ref)
      - name: Cache Node Modules
        uses: actions/cache@v3
        id: cache-modules  # 用于后续步骤判断缓存命中
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # 5. 合并依赖安装步骤（核心优化）
      - name: Install Dependencies
        run: |
          npm install -g hexo-cli  # 全局安装 CLI
          npm install hexo-renderer-pandoc --save  # 安装渲染器
          npm install --force  # 强制修复依赖冲突
        # 验证 Hexo
      - name: Check Hexo Version
        run: hexo -v

      # 6. 生成静态文件
      - name: Build Hexo site
        run: |
          hexo clean
          hexo g  # 生成到 ./public

      # 7. 校验构建结果（关键防御）
      - name: Verify Public Files
        run: |
          if [ ! -f public/index.html ]; then
            echo "ERROR: 构建失败 - public/index.html 未生成"
            exit 1
          fi
          echo "校验通过：检测到 index.html"

      # 8. 配置 Pages 环境
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 9. 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      # 10. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
